server:
  port: 1101

spring:
  application:
    name: huahua-system
  datasource:
    url: jdbc:mysql://${db-ip}:3306/cea?autoRec&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: ****
    password: ****
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: docker

db-ip: localhost

logging:
  level:
    com.kuo.huahua.mapper: debug

---
# Docker
spring:
  config:
    activate:
      on-profile: docker

db-ip: *******

---
# Docker
spring:
  config:
    activate:
      on-profile: dev

db-ip: localhost